sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # google cloud does not show prompts
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # decrypt service-account
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json # access gooogle cloud
  - gcloud config set multi-k8s-383513 # project id
  - gcloud config set compute/zone asia-east1 # compute zone
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker build -t Rubyrubylai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true Rubyrubylai/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
